version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: bitnami
     group: bitnami
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/delete.sh
      runas: root
