version: 0.0
os: linux
files:
   - source: /
     destination: /home/bitnami/htdocs
permissions:
   - object: /home/bitnami/htdocs
     pattern: "**"
     owner: bitnami
     group: bitnami
     mode: 755
     type:
       - file
